application: kakeibo
version: 1
runtime: go
api_version: go1

handlers:
- url: /css
  static_dir: public/css

- url: /scripts
  static_dir: public/scripts

- url: /
  static_files: public/index.html
  upload: public/index.html
  login: required

- url: /.*
  script: _go_app
  login: required
  secure: always
